# Generated by Django 2.0.3 on 2019-01-27 19:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(blank=True, max_length=100)),
                ('gallery_images', models.ImageField(upload_to='images/gallery')),
                ('gallery_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallerys',
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('slugan', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('profile_message', ckeditor.fields.RichTextField()),
                ('web_address', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('facebook_id', models.CharField(blank=True, max_length=200)),
                ('twitter_id', models.CharField(blank=True, max_length=200)),
                ('google_id', models.CharField(blank=True, max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=200)),
                ('linkedin_id', models.CharField(blank=True, max_length=200)),
                ('copyright_name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_for', models.CharField(choices=[('1', 'Family Album'), ('2', 'Toure Albem'), ('3', 'Professional Albem'), ('4', 'Social Albem')], max_length=3)),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('slider_images', models.ImageField(upload_to='images/slider')),
                ('slider_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
            },
        ),
        migrations.AddField(
            model_name='catagory',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='images/category_image'),
        ),
        migrations.AddField(
            model_name='subcatagory',
            name='sub_category_image',
            field=models.ImageField(blank=True, upload_to='images/category_image'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='cat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='sub_category',
            field=models.CharField(max_length=100),
        ),
    ]
