# Generated by Django 2.0.3 on 2019-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190128_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderinfo',
            name='slider_for',
        ),
        migrations.AddField(
            model_name='galleryinfo',
            name='gallery_for',
            field=models.CharField(choices=[('1', 'Family Album'), ('2', 'Toure Albem'), ('3', 'Professional Albem'), ('4', 'Social Albem')], default=0.0004542451271886356, max_length=3),
            preserve_default=False,
        ),
    ]
