# Generated by Django 2.0.3 on 2019-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_catagory_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
