# Generated by Django 2.0.3 on 2019-01-28 16:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190128_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(blank=True, max_length=100)),
                ('operation_title', models.CharField(blank=True, max_length=100)),
                ('operation_details', ckeditor.fields.RichTextField()),
                ('after_images', models.ImageField(upload_to='images/operations')),
                ('before_images', models.ImageField(upload_to='images/operations')),
                ('status', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.SubCatagory')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Add Operation',
            },
        ),
    ]
