# Generated by Django 2.0.3 on 2019-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20190128_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalprofile',
            old_name='company_name',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='copyright_name',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='slugan',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='web_address',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='full_name',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='qualification',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='specialist',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='working_place',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
