# Generated by Django 2.0.3 on 2019-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190129_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/logo'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='specialist',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='working_place',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
