# Generated by Django 2.0.3 on 2019-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20190129_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/logo'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
