# Generated by Django 2.0.3 on 2019-02-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_myaword'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_degree', models.CharField(blank=True, max_length=100)),
                ('institute_name', models.CharField(blank=True, max_length=100)),
                ('passing_year', models.CharField(blank=True, max_length=100)),
                ('CGPA', models.CharField(blank=True, max_length=100)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
