# Generated by Django 2.0.3 on 2019-02-01 07:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_myeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(blank=True, max_length=100)),
                ('award_year', models.CharField(blank=True, max_length=100)),
                ('for_award', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('award_details', ckeditor.fields.RichTextField()),
                ('award_images', models.ImageField(upload_to='images/award')),
                ('status', models.BooleanField(default=True)),
                ('award_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='myAword',
        ),
    ]
