# Generated by Django 2.0.3 on 2019-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20190201_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpost',
            name='operation_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
