# Generated by Django 2.0.3 on 2019-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_operationpost_operation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='myeducation',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
