# Generated by Django 2.0.3 on 2019-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_myeducation_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
