# Generated by Django 2.0.3 on 2019-02-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_gallerycatagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryinfo',
            name='gallery_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.GalleryCatagory'),
        ),
    ]
