# Generated by Django 2.0.3 on 2019-02-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_auto_20190201_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycatagory',
            old_name='category_name',
            new_name='gallery_category',
        ),
    ]
