# Generated by Django 2.0.3 on 2019-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_socialactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='specialist2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='specialist3',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='specialist4',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
